### ISSUE TITLE
Training code?

### ISSUE THREAD

**Issue by Ronsor** [AudiogenAI/agc#1]
Hello

I'm wondering if you have any plans to make the training code available so that it's possible to train a new model or finetune the pretrained one.

**Comment by elyxlz** [comment]
Hi!

Unfortunately we are not looking to release training code for the reason that other repos for training of DAC like architectures already exist:
https://github.com/descriptinc/descript-audio-codec
https://github.com/Stability-AI/stable-audio-tools

It would also be hard to fine tune our existing models and get good results as the checkpoints are EMAed and we have thrown away the original, non averaged weights, you could still try however.

We are still planning to release upcoming codecs, we would like to focus more on speech both data and eval-wise.

Hope you can understand!
